import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from "react"

export default function Home() {
  const [post, setPost] = useState({
    title: "_titulo_",
    description: "_description_",
    image: "_image_",
    url: "_url_",
    site_name: "_site_name_"
  })

  useEffect(() => {
    setTimeout(() => {
      setPost({
        title: "EXPOSICIÓN 'CATÁSTROFE' - DON GUEZ",
        description: "Catástrofe es la primera exposición individual en Suramérica que se ocupa de la práctica del artista Dor Guez, nacido en Jerusalén.",
        image: "https://cartel-urbano-s3.s3.amazonaws.com/static/uploads/8352c8a746b96493cd93-Captura+de+Pantalla+2022-08-08+a+la(s)+11.31.44+a.%C2%A0m..png",
        url: "https://agendacartel.com/evento/arte/exposicion-%22catastrofe%22-don-guez",
        site_name: "CARTEL NEXT"
      })
    }, 1000)
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>{post.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <meta property="og:type" content="article" />
        <meta name="og:title" content={post.title} />
        <meta name="og:description" content={post.description} />
        <meta name="og:image" content={post.image} />
        <meta property="og:url" content={post.url} />
        <meta property="og:site_name" content={post.site_name} />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
